name: Build Aseprite
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 必须包含子模块

      - name: 安装依赖工具
        run: |
          choco install 7zip ninja -y --no-progress

      - name: 下载 Skia 和 libjpeg-turbo
        shell: bash
        run: |
          # 解压本地 skia.zip
          7z x deps/skia.zip -oskia

          # 安装本地 libjpeg-turbo
          mkdir -p third_party/externals/libjpeg-turbo
          ./deps/libjpeg-turbo.exe /S /D=$PWD/third_party/externals/libjpeg-turbo

      - name: 生成构建文件
        shell: bash
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_UI=ON \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=$PWD/skia \
            -DSKIA_LIBRARY_DIR=$PWD/skia/out/Release-x64 \
            -DJPEG_LIBRARY=$PWD/third_party/externals/libjpeg-turbo/lib/jpeg-static.lib \
            -DJPEG_INCLUDE_DIR=$PWD/third_party/externals/libjpeg-turbo/include

      - name: 编译
        run: cd build && ninja

      - name: 打包成品
        uses: actions/upload-artifact@v4
        with:
          name: aseprite
          path: |
            build/bin/aseprite.exe
            build/bin/data/*
